### PR TITLE
rename resourceQoS to resourceQOS

### PR DESCRIPTION
**Pull request by zwzhang0107**
Signed-off-by: 佑祎 <zzw261520@alibaba-inc.com>

### Ⅱ. Does this pull request fix one issue?

#340

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by saintube — COMMENTED** [review]
@zwzhang0107 do we need to rename `QoSClass` (in file `apis/extension/qos.go`) to `QOSClass`?

**Comment by zwzhang0107** [comment]
> rename

maybe later since the protocol is already as "qosClass" format

**Pull request merged**
