### PR TITLE
Add a new adopter

### PR DESCRIPTION
**Pull request by j4ckstraw**
### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by j4ckstraw** [comment]
cc @jiasheng55

**Comment by hormes** [comment]
Wellcome!

**Comment by ZiMengSheng** [comment]
Wellcome!

**Comment by eahydra** [comment]
Welcome! 🎉 🚀  🎉 🚀  🎉 🚀  🎉 🚀

**Comment by saintube** [comment]
Long awaited, welcome!

**Comment by jasonliu747** [comment]
Welcome！！！

/lgtm

**Review by hormes — APPROVED** [review]

**Pull request merged**
