### PR TITLE
scheduler: elastic quota ignore terminating pod immediately

### PR DESCRIPTION
**Pull request by TaoYang526**
### Ⅰ. Describe what this PR does

proposal: #2179 
introduce a feature gate called ElasticQuotaImmediateIgnoreTerminatingPod, which would allow to bypass the deletion grace period and immediately ignore terminating pods.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by TaoYang526** [comment]
@saintube Thanks for reminding that, just updated.

**Comment by saintube** [comment]
/lgtm
PTAL /cc @shaloulcy

**Comment by saintube** [comment]
/lgtm
PTAL /cc @shaloulcy @ZiMengSheng @hormes

**Review by hormes — APPROVED** [review]

**Pull request merged**
