### PR TITLE
koordlet: fix error in perf collector

### LINKED ISSUE #1568: [BUG] koordlet close cgroup file error and cannot collect cycles
**What happened**:
While using koordlet version v1.3.0, and after activating the performance collector feature, an error arises during the closure of cgroup files upon perf data collection. The error message is as follows:
```text
E0822 17:41:55.375473 1723326 performance_collector_linux.go:156] PerfCollector cleanup err : close cgroupFile /host-cgroup/kubepods.slice/xxx.scope, err : close /host-cgroup/kubepods.slice/xxx.scope: file already closed
```
and the result of cycles is 0(the result of instructions is not 0)
```text
koordlet_container_cpi{container_id="containerd://xxx",container_name="xxx",cpi_field="cycles",node="xxx",pod_name="xxx",pod_namespace="xxx",pod_uid="xxx"} 0
koordlet_container_cpi{container_id="containerd://xxx",container_name="xxx",cpi_field="instructions",node="xxx",pod_name="xxx",pod_namespace="xxx",pod_uid="xxx"} 3.46941397e+09
```
**What you expected to happen**:
No Error, the result of cycles is not 0.
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a ns and create a deployment which has 100 nginx instances.
2. Install koordinator and enable `CPI`, `PSI`.
3. Use `kubectl` get the log of `koordlet`. Use `curl` get the metrics.

**Anything else we need to know?**:
Use `perf` can get right result.
**Environment**:
- App version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.27.2
- Install details (e.g. helm install args): helm install koordinator koordinator-sh/koordinator --version 1.3.0
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:1.7.1
  - OS version:Ubuntu 22.04
  - Kernal version:5.15.0-79-generic
  - Cgroup driver: cgroupfs
- Others:

### PR DESCRIPTION
**Pull request by bowen-intel**
### Ⅰ. Describe what this PR does
Fix cycles value is 0 error and cgroup file close twice error.

### Ⅱ. Does this pull request fix one issue?
fixes #1568 

### Ⅲ. Describe how to verify it
Prometheus and log system.
### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by songtao98 — COMMENTED** [review]
/lgtm

**Comment by bowen-intel** [comment]
@zwzhang0107 
Any comments?

**Pull request merged**
