### PR TITLE
chore: refactor cpuset in package for code reuse

### PR DESCRIPTION
**Pull request by eahydra**
Signed-off-by: Joseph <joseph.t.lee@outlook.com>

### Ⅰ. Describe what this PR does

There are multiple implementations of cpuset in the current code, which are now refactored and integrated.

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by ZiMengSheng — APPROVED** [review]

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Review by saintube — APPROVED** [review]
/lgtm

**Pull request merged**
