### PR TITLE
koordlet: add batch resource utils

### PR DESCRIPTION
**Pull request by saintube**
Signed-off-by: saintube <saintube@foxmail.com>

### Ⅰ. Describe what this PR does

add utility functions for extended batch resources (`batch-cpu` and `batch-memory`)

### Ⅱ. Does this pull request fix one issue?

It is for extensity reasons. The retrieval of batch resources is wrapped in utility functions, with which we can support other resource names easily.

### V. Checklist

- [X] I have written necessary docs and comments
- [X] I have added necessary unit tests and integration tests
- [X] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
