### PR TITLE
runtime-proxy: refactor runtime-proxy service framework

### PR DESCRIPTION
**Pull request by xigang**
### Ⅰ. Describe what this PR does
runtime-proxy: refactor runtime-proxy service framework.

### Ⅱ. Does this pull request fix one issue?

```
NONE
```

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — COMMENTED** [review]
@xigang thanks for your hard work. Patch coverage is only 18.75%, it would be appreciated if you could add some unit tests to improve it.

**Comment by xigang** [comment]
> @xigang thanks for your hard work. Patch coverage is only 18.75%, it would be appreciated if you could add some unit tests to improve it.

okay, I will add some unit tests later:)

**Comment by xigang** [comment]
> @xigang thanks for your hard work. Patch coverage is only 18.75%, it would be appreciated if you could add some unit tests to improve it.

@jasonliu747 Add some unit tests, take a look.

**Pull request closed without merging**
