### PR TITLE
koordlet: fix node aggregate policy config

### PR DESCRIPTION
**Pull request by saintube**
### Ⅰ. Describe what this PR does

1. Fix the example of aggregating policy in the `slo-controller-config`.
2. Fix the node aggregating policy configuration of the node metric.

### V. Checklist

- [X] I have written necessary docs and comments
- [X] I have added necessary unit tests and integration tests
- [X] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
