### PR TITLE
apis: introduce api for node resource amplification

### PR DESCRIPTION
**Pull request by zqzten**
### Ⅰ. Describe what this PR does

This PR introduces API and its utils for for node resource amplification.

### Ⅱ. Does this pull request fix one issue?

Part of #1539

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by saintube** [comment]
/lgtm
PTAL @eahydra

**Review by eahydra — COMMENTED** [review]
/lgtm

**Review by hormes — APPROVED** [review]

**Pull request merged**
