### PR TITLE
koordlet: fix by adding lock during podmap update

### PR DESCRIPTION
**Pull request by xujihui1985**
add write lock during podmap update, otherwise there is potential race condition

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — COMMENTED** [review]
/lgtm
/approve

**Comment by xujihui1985** [comment]
thanks

**Pull request merged**
