### PR TITLE
koord-scheduler: eliminate unnecessary memory overhead and lock conflicts

### PR DESCRIPTION
**Pull request by eahydra**
### Ⅰ. Describe what this PR does

Conduct a performance test on the scheduler and find some unnecessary memory overhead and lock conflicts.

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by saintube — COMMENTED** [review]
/lgtm

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
