### PR TITLE
koord-manager: nodeslo-controller enqueue request when node labels updated

### PR DESCRIPTION
**Pull request by chengjoey**
### Ⅰ. Describe what this PR does
#2116
enqueue request when node update labels

### Ⅲ. Describe how to verify it
running in local

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by chengjoey** [comment]
cc @songtao98

**Comment by songtao98** [comment]
Good job! Thanks :)
/lgtm

**Comment by songtao98** [comment]
cc @zwzhang0107

**Pull request merged**
