### PR TITLE
koord-scheduler: ElasticQuota supports Decorator to decorate Node, Pod and ElasticQuota

### PR DESCRIPTION
**Pull request by eahydra**
Signed-off-by: Joseph <joseph.t.lee@outlook.com>

### Ⅰ. Describe what this PR does

ElasticQuota scheduling plugin supports `Decorator` interface to decorate Node, Pod and ElasticQuota as needed. 
For example, if you want to append some additional resources into Node, Pod and ElasticQuota such as GPU Resources or modify Spec by GPU model, you can implement the Decorator interface. 

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by eahydra** [comment]
@xulinfei1996

**Review by buptcozy — APPROVED** [review]
/approve

**Review by buptcozy — COMMENTED** [review]
/lgtm

**Pull request merged**
