### PR TITLE
vendor: goodbye vendor

### LINKED ISSUE #145: [proposal] remove vendor dependencies
**What is your proposal**:
Now that we have switched to Go modules, there's no need to commit dependencies in the vendoring directory to the repository. I don't see much value in keeping in the repo and it just adds bloat.

For users in China, there're lot of modules in the Go ecosystem that cannot be easily`go install`. In that case, they can follow the instruction below to fix this problem.

```
$ go env -w GO111MODULE=on
$ go env -w GOPROXY=https://goproxy.cn,direct
```

### PR DESCRIPTION
**Pull request by jasonliu747**
Signed-off-by: Jason Liu <jasonliu747@gmail.com>

### Ⅰ. Describe what this PR does
Remove `vendor` in root directory.

### Ⅱ. Does this pull request fix one issue?

Fixes #145

### CODE REVIEW

**Comment by zwzhang0107** [comment]
some checks failure needs to be fixed

**Comment by jasonliu747** [comment]
> some checks failure needs to be fixed

fixed

**Pull request merged**
