### PR TITLE
ci: support running unit test on multiple os

### LINKED ISSUE #163: [support request] Run GitHub Action on multiple environments
**What is your problem or scenario?**
Since majority of programmer are using Mac for development, and deploy Koordinator in a Linux environment. So after #151 , I think it's necessary to run github action on multiple environments like MacOS and Linux.

### PR DESCRIPTION
**Pull request by jasonliu747**
Signed-off-by: Jason Liu <jasonliu747@gmail.com>

### Ⅰ. Describe what this PR does
Since majority of programmer are using Mac for development, and deploy Koordinator in a Linux environment. So after https://github.com/koordinator-sh/koordinator/pull/151 , I think it's necessary to run github action on multiple environments like MacOS and Linux.

### Ⅱ. Does this pull request fix one issue?

fixes #163

### CODE REVIEW

**Comment by hormes** [comment]
It might be too slow to run on Mac, can it be made optional？

**Comment by jasonliu747** [comment]
> It might be too slow to run on Mac, can it be made optional？

@hormes I've tried almost every possible solution but without success. Let's merge this PR firtst, and I'll open an issue in [here](https://github.com/actions/virtual-environments).

**Pull request merged**
