### PR TITLE
docs: what is a good pull request

### PR DESCRIPTION
**Pull request by jasonliu747**
Signed-off-by: Jason Liu <jasonliu747@gmail.com>

### Ⅰ. Describe what this PR does
This PR introduce the proper workflow of creating a pull request in Koordinator Organization.

### Ⅳ. Special notes for reviews
Let's go through this document in the upcoming weekly meeting before merging it.

### CODE REVIEW

**Comment by hormes** [comment]
This is a very good PR template =.=

**Comment by jasonliu747** [comment]
> This is a very good PR template =.=

image

**Comment by ZYecho** [comment]
good pr also need sign off, WDYT?

**Pull request merged**
