### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by zhouzijiang**
### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by zwzhang0107** [comment]
welcome!
/lgtm

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Comment by hormes** [comment]
Very excited to see that koordinator can help customers' real production environment.

**Review by hormes — APPROVED** [review]

**Comment by flpanbin** [comment]
@zhouzijiang  Hi, Can you share some usage experience about [koordinator](https://github.com/koordinator-sh/koordinator)? What specific functions were used and what problems were solved? thanks a lot.

**Pull request merged**
