### PR TITLE
Add OWNERS files for approvers definition and update community docs

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does

Add OWNERS files for approvers definition and update community docs.

### CODE REVIEW

**Comment by FillZpp** [comment]
@jasonliu747  I expect those approvers could post PRs to add them into the approver alias, or I can complete the alias for all of them. Which one do you think is better?

**Review by jasonliu747 — APPROVED** [review]
@FillZpp sure, SGTM.
/lgtm

**Pull request merged**
