### PR TITLE
koordlet: remove deprecated BEReconcile

### LINKED ISSUE #836: [proposal] abandon the origin feature `be_reconcile.go` in res-manager
**What is your proposal**:
delete the feature and file `be_reconcile.go`

**Why is this needed**:
#774 has moved the extend-resource reconciling to runtime-hooks, the origin feature should be abandoned

**Is there a suggested solution, if so, please add it**:

### PR DESCRIPTION
**Pull request by saintube**
Signed-off-by: saintube <saintube@foxmail.com>

### Ⅰ. Describe what this PR does

remove the deprecated koordlet's feature `BEReconcile`, while the cgroup reconciliation for BE pods is done in the runtime hook's feature `BatchResource`.

### Ⅱ. Does this pull request fix one issue?

fixes #836.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by FillZpp** [comment]
> /hold until #887 gets merged

It has been merged.

**Comment by saintube** [comment]
> > /hold until #887 gets merged
> 
> It has been merged.

Updated. 
cc @zwzhang0107 @jasonliu747 @FillZpp @hormes @eahydra

**Comment by saintube** [comment]
/unhold
cc @zwzhang0107 @jasonliu747 @FillZpp @hormes @eahydra

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
