### PR TITLE
refactor: replace deprecated pointer function with the recommended pointer function

### PR DESCRIPTION
**Pull request by Gala-R**
…inter function

### Ⅰ. Describe what this PR does

replace deprecated pointer function with the recommended pointer function.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by eahydra — APPROVED** [review]
/lgtm
/approve

**Review by eahydra — APPROVED** [review]
/lgtm
/approve

**Review by eahydra — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
