### PR TITLE
Release v1.4.1

### PR DESCRIPTION
**Pull request by saintube**
### Ⅰ. Describe what this PR does

Release v1.4.1, including several bugfixes and necessary improvements after releasing v1.4.0.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Review by eahydra — COMMENTED** [review]
/lgtm

**Comment by saintube** [comment]
See https://github.com/koordinator-sh/koordinator/releases/tag/v1.4.1

**Pull request closed without merging**
