### PR TITLE
scheduler: DeviceShare supports numa-aware scheduling

### PR DESCRIPTION
**Pull request by eahydra**
### Ⅰ. Describe what this PR does

DeviceShare supports numa-aware scheduling.

implements #228 - koord-scheduler supports NUMA Topology Alignment scheduling with Device

### CODE REVIEW

**Comment by eahydra** [comment]
ping @hormes @jasonliu747 @ZiMengSheng

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Pull request merged**
