### PR TITLE
just tidy up some logic

### PR DESCRIPTION
**Pull request by lucming**
Signed-off-by: lucming <2876757716@qq.com>

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by hormes** [comment]
cool, are you trying to use koordinator in internal environment? looking forward to hearing your voice: https://github.com/koordinator-sh/koordinator/issues/466

**Review by jasonliu747 — COMMENTED** [review]
/lgtm
thanks for your contribution.

**Comment by lucming** [comment]
> cool, are you trying to use koordinator in internal environment? looking forward to hearing your voice: #466

yes,we intend to something about mixed deploy,this project will be used as a shelf.

**Pull request merged**
