### PR TITLE
runtime-proxy: extract annotations from labels for docker

### PR DESCRIPTION
**Pull request by Solomonwisdom**
### Ⅰ. Describe what this PR does

runtime-proxy: extract annotations from labels for docker

In dockershim，annotations and labels are merged because docker supports only labels.
We should extract annotations from labels for docker in failOver as we do in HandleCreateContainer of RuntimeManagerDockerServer.

### Ⅱ. Does this pull request fix one issue?

None

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by hormes** [comment]
Why do you need to do this, can you add some description to help everyone understand its purpose?

**Comment by Solomonwisdom** [comment]
In dockershim，annotations and labels are merged because docker supports only labels.
We should extract annotations from labels for docker in failOver as we do in HandleCreateContainer of RuntimeManagerDockerServer.
You can look [this](https://github.com/koordinator-sh/koordinator/blob/main/pkg/runtimeproxy/server/docker/handler.go#L57)

**Comment by hormes** [comment]
I got it, thanks for contributing this pr.

**Review by hormes — APPROVED** [review]

**Pull request merged**
