### PR TITLE
Activate rdt res_ctrl in resmanager

### PR DESCRIPTION
**Pull request by cheimu**
Signed-off-by: cheimu yimo@xiaohongshu.com

### Ⅰ. Describe what this PR does
https://github.com/koordinator-sh/koordinator/pull/94#issuecomment-1120709905

### CODE REVIEW

**Comment by jasonliu747** [comment]
@cheimu Nice, thanks for your contribution. Please follow the instruction to fix the DCO error.😁

**Comment by cheimu** [comment]
> @cheimu Nice, thanks for your contribution. Please follow the instruction to fix the DCO error.😁

Done. 😄

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Pull request merged**
