### PR TITLE
fix: Walkfunc should check the err

### PR DESCRIPTION
**Pull request by j4ckstraw**
Signed-off-by: j4ckstraw <j4ckstraw@foxmail.com>

### Ⅱ. Does this pull request fix one issue?
fix https://github.com/koordinator-sh/koordinator/issues/459

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by j4ckstraw** [comment]
fix #459

**Comment by saintube** [comment]
@j4ckstraw Could you please add a unit test for this fix?

**Comment by j4ckstraw** [comment]
> @j4ckstraw Could you please add a unit test for this fix?

Let me try

**Comment by jasonliu747** [comment]
@j4ckstraw any progress with this PR?

**Comment by j4ckstraw** [comment]
> @j4ckstraw any progress with this PR?

sorry, I am busy recently.

BYW, Is it really need a test?

**Comment by jasonliu747** [comment]
> 
> BYW, Is it really need a test?

Actually no, but we would love to see the code coverage getting higher. We can still merge this PR if you want, it's your call, please let me know.

**Comment by saintube** [comment]
> > @j4ckstraw any progress with this PR?
> 
> sorry, I am busy recently.
> 
> BYW, Is it really need a test?

We will appreciate it if you can make a testable patch and help us avoid regression.

**Comment by j4ckstraw** [comment]
I have a problem when try to write a test for this function.

I know that if the path which stat call is not found, the Walk function will return error.
BUT `rootCgroupPath` is checked before walk, so I can't reproduce this error conveniently.  https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/resmanager/cpu_suppress.go#L78

Now I can reproduce only in race condition, I have no idea to write a test for it. help!

**Comment by jasonliu747** [comment]
Hi @j4ckstraw, please rebase to the latest code. Codecov won't be a problem anymore, we can merge this PR then.

**Comment by jasonliu747** [comment]
@j4ckstraw have you joined our DingTalk or WeChat group? I would like to discuss further cooperation with you~

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Comment by j4ckstraw** [comment]
> @j4ckstraw have you joined our DingTalk or WeChat group? I would like to discuss further cooperation with you~

Not yet, It would be my pleasure.

**Comment by jasonliu747** [comment]
> 
> Not yet, It would be my pleasure.

Nice! You can find our DingTalk QR Code in [README](https://github.com/koordinator-sh/koordinator#community)

**Comment by j4ckstraw** [comment]
> > Not yet, It would be my pleasure.
> 
> Nice! You can find our DingTalk QR Code in [README](https://github.com/koordinator-sh/koordinator#community)
Got it, I have joined in it.

**Pull request merged**
