### PR TITLE
apis: add host application metric to node metric crd

### PR DESCRIPTION
**Pull request by zwzhang0107**
### Ⅰ. Describe what this PR does

add apis for reporting metric of host application, this can be also used for reporting the whole yarn task resource usage.

For out-of-band applications with batch priority, resource calculation of batch allocatable should excluded their usage, otherwise it will be count into system usage.

### Ⅱ. Does this pull request fix one issue?

#1639

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Review by saintube — APPROVED** [review]
/lgtm

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
