### PR TITLE
🌱 add unit test for memory evict feature

### PR DESCRIPTION
**Pull request by jasonliu747**
Signed-off-by: Jason Liu <jasonliu747@gmail.com>

### Ⅰ. Describe what this PR does
add ut for memory evict feature

### CODE REVIEW

**Comment by hormes** [comment]
Why is the unit-test coverage not increasing but decreasing?

**Comment by jasonliu747** [comment]
> Why is the unit-test coverage not increasing but decreasing?

IKR, that's so werid. Coverage also decreased after #118 merged.

**Comment by hormes** [comment]
image

unmodified files show different results, so weird.

**Pull request merged**
