### PR TITLE
koord-yarn: add pkg dir for YARN related modules

### PR DESCRIPTION
**Pull request by zwzhang0107**
### Ⅰ. Describe what this PR does

add some pkg dirs for YARN related modules, see https://github.com/koordinator-sh/koordinator/discussions/1297 for detailed desgins.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by eahydra** [comment]
Is it more reasonable to create a yarn directory specifically, and then create a copilot/operator below it? The subsequent yarn-specific code can be converged. This keeps the same style as webhook/descheduler/scheduler/koordlet.

**Comment by FillZpp** [comment]
`operator` is a little weird name as a sub package under `pkg`, which is usually the name of the whole project or component. How about `controller` or `controllers`?

**Review by FillZpp — APPROVED** [review]
/lgtm

**Review by hormes — APPROVED** [review]

**Pull request merged**
