### PR TITLE
scheduler: support scheduler config v1

### PR DESCRIPTION
**Pull request by AdrianMachao**
### Ⅰ. Describe what this PR does

support scheduler config v1

### Ⅱ. Does this pull request fix one issue?

fix https://github.com/koordinator-sh/koordinator/issues/2165

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by saintube** [comment]
@AdrianMachao Good job!
Could you please add the example config under the directory `config/manager`? So we can verify the upgrade during the E2E tests.

**Comment by AdrianMachao** [comment]
> @AdrianMachao Good job! Could you please add the example config under the directory `config/manager`? So we can verify the upgrade during the E2E tests.

got it

**Comment by AdrianMachao** [comment]
> @AdrianMachao Good job! Could you please add the example config under the directory `config/manager`? So we can verify the upgrade during the E2E tests.

ok, I will upgrade config/manager/scheduler-config.yaml version to  v1

**Comment by saintube** [comment]
> > @AdrianMachao Good job! Could you please add the example config under the directory `config/manager`? So we can verify the upgrade during the E2E tests.
> 
> updated, is it that？

Yes. /lgtm
PTAL /cc @ZiMengSheng

**Comment by saintube** [comment]
> > @AdrianMachao Good job! Could you please add the example config under the directory `config/manager`? So we can verify the upgrade during the E2E tests.
> 
> updated, is it that？

Yes.
/lgtm
PTAL /cc @ZiMengSheng

**Pull request merged**
