### PR TITLE
proposal: CPU Normalization

### PR DESCRIPTION
**Pull request by zqzten**
This is the proposal of #1570.

### CODE REVIEW

**Comment by zqzten** [comment]
Update: Move the scheduler part to #1700 and update some impl details with the latest actual impls.

/unhold PTAL @hormes

**Comment by zqzten** [comment]
Update: Move the scheduler part to https://github.com/koordinator-sh/koordinator/pull/1700 and update some impl details with the latest actual impls.

/unhold
PTAL @hormes

**Review by hormes — APPROVED** [review]

**Pull request merged**
