### PR TITLE
koordlet:encapsulating reused logics(updatePodCFSQuota,updateContainerCFSQuota)

### PR DESCRIPTION
**Pull request by lucming**
### Ⅰ. Describe what this PR does
1. encapsulating reused logics 
    eg:  update CFSQuota of pod, update CFSQuota of Container
    this part of logic is used in many places,maybe better to encapsulated as a function
2.  reducing some logic nesting

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by saintube** [comment]
@lucming We are planning to refactor the cgroup updates in #720. It may change the implementation for updating pod/container cfs_quota. Could you please hold the encapsulation until the refactoring is done?

**Comment by lucming** [comment]
> @lucming We are planning to refactor the cgroup updates in #720. It may change the implementation for updating pod/container cfs_quota. Could you please hold the encapsulation until the refactoring is done?

okay.

**Comment by saintube** [comment]
/unhold
@lucming Hi, now it's okay to revise the updating of pod/container cfs_quota with the new ResourceExecutor module. Please feel free to continue this work at any time.

**Comment by lucming** [comment]
> /unhold @lucming Hi, now it's okay to revise the updating of pod/container cfs_quota with the new ResourceExecutor module. Please feel free to continue this work at any time.

okay.

**Pull request merged**
