### PR TITLE
koordlet: fix typo in function isBECPUUsageHighEnough

### LINKED ISSUE #1825: [question] question about isBECPUUsageHighEnough
does this mean if only 1 core left for BE pod, we decide BECPUUsageHighEnough?

_Originally posted by @j4ckstraw in https://github.com/koordinator-sh/koordinator/pull/1451#discussion_r1445796553_

### PR DESCRIPTION
**Pull request by j4ckstraw**
### Ⅰ. Describe what this PR does

fix #1825 

### V. Checklist

- [x] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by j4ckstraw** [comment]
shall we add a test for isBECPUUsageHighEnough? or calculateMilliRelease?

**Comment by jasonliu747** [comment]
> shall we add a test for isBECPUUsageHighEnough? or calculateMilliRelease?

that would be great!

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Pull request merged**
