### PR TITLE
koord-descheduler: Fix threshold initialization for prod.

### PR DESCRIPTION
**Pull request by zwForrest**
### Ⅰ. Describe what this PR does
Fix threshold initialization for prod when useDeviationThresholds mode is true. Add more debug log.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

**Comment by zwForrest** [comment]
@songtao98 PTAL

**Review by hormes — APPROVED** [review]

**Pull request merged**
