### PR TITLE
cleanup: Use the structure as the key of the map instead of string

### PR DESCRIPTION
**Pull request by novahe**
### Ⅰ. Describe what this PR does
Use the structure as the key of the map instead of string

refer：
https://github.com/golang/groupcache/blob/41bb18bfe9da5321badc438f91158cd790a33aa3/lru/lru.go#L36-L37

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by ZYecho** [comment]
thanks for your pr
please squash your commits

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Pull request merged**
