### PR TITLE
rename runtime-hook working mode (Bypass->Standalone)

### PR DESCRIPTION
**Pull request by novahe**
### Ⅰ. Describe what this PR does
refer to #283 and fix docs/images/runtime-hooks-working-mode.svg

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by jasonliu747** [comment]
Hi @novahe nice catch! Please sign off your commit, and other than that, we're all good.

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Comment by novahe** [comment]
hi @jasonliu747  signed off it ~ PTAL!

**Comment by hormes** [comment]
@novahe nice work~

**Pull request merged**
