### PR TITLE
koordlet: add event cache for audit log

### PR DESCRIPTION
**Pull request by LeoLiuYan**
Signed-off-by: LeoLiuYan <929908264@qq.com>

### Ⅰ. Describe what this PR does

As the title says.

### Ⅱ. Does this pull request fix one issue?

NONE

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by jasonliu747** [comment]
What's the background for this feature?

**Comment by LeoLiuYan** [comment]
> What's the background for this feature?

There are a lot of redundant events in `audit.log`, it's confusion to users which want to select the valuable events.  
So it's better to add event cache to reduce the repetitive events.

@jasonliu747

**Comment by hormes** [comment]
The write operations of cgroups have been cached, maybe we can adjust the point of writing the log to solve the problem of repeated events?

**Comment by LeoLiuYan** [comment]
> The write operations of cgroups have been cached, maybe we can adjust the point of writing the log to solve the problem of repeated events?

The `resourceexecutor` package which responsibility for write cgroups has cached part of audit log, that's true. But it may be not enough to reduce repeated events because of logging the audit operation have scattered elsewhere, for example:  https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/runtimehooks/protocol/container_context.go#L177.

Another viewpoint,  the cache of audit log may have longer gc time than `resourceexecutor` package.

@hormes

**Comment by LeoLiuYan** [comment]
So, should we add cache capability in audit package?   @jasonliu747 @hormes

**Comment by hormes** [comment]
> So, should we add cache capability in audit package? @jasonliu747 @hormes

The cache may be a little heavy, is there a lighter way?

**Comment by zwzhang0107** [comment]
new module `koordlet/resourceexecutor` has been added, which has supported for cacheable read/write for cgroup file,  how about using these cacheable method and add audit log. This may solve the redundant logs. @LeoLiuYan

**Comment by LeoLiuYan** [comment]
> > So, should we add cache capability in audit package? @jasonliu747 @hormes
> 
> The cache may be a little heavy, is there a lighter way?



> > So, should we add cache capability in audit package? @jasonliu747 @hormes
> 
> The cache may be a little heavy, is there a lighter way?

May be the cache is already lightweight?  Do we have an easy way?

**Comment by LeoLiuYan** [comment]
> > The write operations of cgroups have been cached, maybe we can adjust the point of writing the log to solve the problem of repeated events?
> 
> The `resourceexecutor` package which responsibility for write cgroups has cached part of audit log, that's true. But it may be not enough to reduce repeated events because of logging the audit operator have scattered elsewhere, for example: https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/runtimehooks/protocol/container_context.go#L177.
> 
> Another viewpoint, the cache of audit log may have longer gc time than in `resourceexecutor` package.
> 
> @hormes

/cc @zwzhang0107

**Comment by hormes** [comment]
Let's sort it out first, the current auditor is used to audit key resource changes, and it is quite dependent on the order of changes. Therefore, let's first look at which changes are frequent and ineffective, and then discuss feasible solutions together. Using event cache directly to deduplicate may violate the original intention. Of course, this whole thing can be discussed and changed.

**Comment by LeoLiuYan** [comment]
I found out the main places where logging the audit events by searching `audit.V` keyword.

- package `koordlet/qosmanager`

    -  `cpu_suppress.go:359`    
        The command is: `audit.V(1).Node().Reason(resourceexecutor.AdjustBEByNodeCPUUsage).Message("update BE group to cpuset: %v", beCPUSet).Do()`.
        
        It will log events in fixed interval.

   
- package `koordlet.runtimehooks`

  -  `hooks/groupidentity/rule.go:138`
       The command is: `audit.V(2).Group(string(kubeQOS)).Reason(name).Message("set bvt to %v", bvtValue)`

      It will log events many times in one reconcile.

**Comment by zwzhang0107** [comment]
i recommend that let `resource executor` do the audit log, since it is already cachable.
so maybe there are two jobs:
1. use `resource executor` for all cgroups file writes (most are already done)
2. mv audit log to `resource executor`, e.g. ResourceUpdateExecutorImpl.updateByCache

**Comment by zwzhang0107** [comment]
> i recommend that let `resource executor` do the audit log, since it is already cachable. so maybe there are two jobs:
> 
> 1. use `resource executor` for all cgroups file writes (most are already done)
> 2. mv audit log to `resource executor`, e.g. ResourceUpdateExecutorImpl.updateByCache

what do you think about this, we can start some new issues to follow. @LeoLiuYan

**Comment by LeoLiuYan** [comment]
I agree with you.    @zwzhang0107 
What do you think ? @hormes

**Comment by Re-Grh** [comment]
new issues here

**Comment by zwzhang0107** [comment]
since the new issue has been created, we will close this issue in following days

**Comment by zwzhang0107** [comment]
now you can follow this PR #1055 @LeoLiuYan

**Pull request closed without merging**
